// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct ProxyServer ProxyServer;
void __swift_bridge__$ProxyServer$_free(void* self);

void* __swift_bridge__$Vec_ProxyServer$new(void);
void __swift_bridge__$Vec_ProxyServer$drop(void* vec_ptr);
void __swift_bridge__$Vec_ProxyServer$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_ProxyServer$pop(void* vec_ptr);
void* __swift_bridge__$Vec_ProxyServer$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_ProxyServer$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_ProxyServer$len(void* vec_ptr);
void* __swift_bridge__$Vec_ProxyServer$as_ptr(void* vec_ptr);

void* __swift_bridge__$ProxyServer$new(void);
void __swift_bridge__$ProxyServer$start(void* callback_wrapper, void __swift_bridge__$ProxyServer$start$async(void* callback_wrapper), void* self);
void __swift_bridge__$ProxyServer$stop(void* callback_wrapper, void __swift_bridge__$ProxyServer$stop$async(void* callback_wrapper), void* self);
bool __swift_bridge__$ProxyServer$is_running(void* self);
void* __swift_bridge__$ProxyServer$get_uris(void* self);
void __swift_bridge__$no_used(void* _str);


